### PR TITLE
refactor: Set fish_config with $__fish_config_dir

### PR DESCRIPTION
**Pull request by SirWrexes**
Hello,
Is this to your liking ?
Have a good day. :wave:

### CODE REVIEW

**Review by joseluisq — CHANGES_REQUESTED** [review]
Everything is fine. The only minor change that you could do taking advantage of your PR is this one on line 15:

```diff
-set -q GITNOW_CONFIG_FILE; or set -g GITNOW_CONFIG_FILE ~/.gitnow
+set -q GITNOW_CONFIG_FILE; or set -g GITNOW_CONFIG_FILE "$HOME/.gitnow"
```

**Comment by SirWrexes** [comment]
Well I know it's a very rare occurrence but I did happen to have some programs not recognise '~' once or twice, whereas expanding an environment variable should always work and I don't really see how `$HOME` could be missing from the environment when spawning a shell.
I guess it's mostly a preference thing in the end though.
Shall I do the change ?

**Comment by joseluisq** [comment]
> Well I know it's a very rare occurrence but I did happen to have some programs not recognise '~' once or twice, whereas expanding an environment variable should always work and I don't really see how `$HOME` could be missing from the environment when spawning a shell.

`$HOME` env is part of POSIX specification which means it must be present on system.  

> I guess it's mostly a preference thing in the end though.

Yes, just concordance with your PR. But yeah in practice both are essentially the same.

> Shall I do the change ?

It is just a suggestion for "convention only" since your are introducing a `$HOME` too.
BTW this is the only place where `~` is used for paths.

**Comment by SirWrexes** [comment]
Alrighty then !

**Comment by joseluisq** [comment]
Thanks!

**Comment by joseluisq** [comment]
Published on release [2.8.0](https://github.com/joseluisq/gitnow/releases/tag/2.8.0)

**Pull request merged**
