### PR TITLE
Remove unnecessary repainting jobs.

### PR DESCRIPTION
**Pull request by shadyar-bk**

### CODE REVIEW

**Comment by shadyar-bk** [comment]
I have faced a problem with commit-all before and after editing the files.

I have removed my prompt and any other add-ons. I was wondering if it is working on your side.

**Review by joseluisq — APPROVED** [review]
I found no issues on Macos. Tested `commit-all` also with no problems.
I will do a final test on Linux in few hours.

**Comment by shadyar-bk** [comment]
Great!

**Comment by joseluisq** [comment]
Verified on Linux.
Thanks

**Pull request merged**
