### PR TITLE
Add completions for move command

### PR DESCRIPTION
**Pull request by ivaaaan**
Hey. I really like the plugin and would like to contribute. Let me know if it needs more completions or I need to add sth else

### CODE REVIEW

**Comment by joseluisq** [comment]
Sure, completions are a missing feature so feel free to contribute with more ones.

**Comment by joseluisq** [comment]
Have you tried to install it? I got errors

```sh
~> fisher add ivaaaan/gitnow@fish-completions
linking ~/.config/fish/functions/__gitnow_config_file.fish
linking ~/.config/fish/functions/__gitnow_functions.fish
linking ~/.config/fish/functions/__gitnow_manual.fish
linking ~/.config/fish/completions/__gitnow_completions.fish
linking ~/.config/fish/conf.d/gitnow.fish
linking ~/.config/fish/conf.d/gitnow_config.fish
source: Error encountered while sourcing file '/completions/__gitnow_completions.fish':
source: No such file or directory
source: Error encountered while sourcing file '/completions/__gitnow_completions.fish':
source: No such file or directory
source: Error encountered while sourcing file '/completions/__gitnow_completions.fish':
source: No such file or directory
source: Error encountered while sourcing file '/completions/__gitnow_completions.fish':
source: No such file or directory
source: Error encountered while sourcing file '/completions/__gitnow_completions.fish':
source: No such file or directory
source: Error encountered while sourcing file '/completions/__gitnow_completions.fish':
source: No such file or directory
source: Error encountered while sourcing file '/completions/__gitnow_completions.fish':
source: No such file or directory
fetching https://codeload.github.com/fishpkg/fish-segment/tar.gz/master
fetching https://codeload.github.com/fishpkg/fish-pwd-info/tar.gz/master
fetching https://codeload.github.com/fishpkg/fish-git-util/tar.gz/master
fetching https://codeload.github.com/fishpkg/fish-pwd-is-home/tar.gz/master
```

**Comment by ivaaaan** [comment]
@joseluisq should be fine now.

**Comment by joseluisq** [comment]
Fine, it works now.

**Review by joseluisq — APPROVED** [review]

**Comment by joseluisq** [comment]
Merged!
It's also included in future `v2.5.0` but you can use this feature PR right now reinstalling GitNow from master branch.

Thanks.

**Pull request merged**
